version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ./.tmp/prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager:/config
      - ./.tmp/alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - "./config/grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./.tmp/minio-data-1-1:/data1
      - ./.tmp/minio-data-1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./.tmp/minio-data-2-1:/data1
      - ./.tmp/minio-data-2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - ./.tmp/minio-data-3-1:/data1
      - ./.tmp/minio-data-3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - ./.tmp/minio-data-4-1:/data1
      - ./.tmp/minio-data-4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./config/minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  postgres_db:
    image: "postgres"
    ports:
      - '5433:5432'
    volumes:
      - ./.tmp/database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: sandox
