version: 1
settings:
  exporter:
    name: edge-devices
    port: 2225
    idle: 30
datasources:
  databases:
    - name: devices_db
      dialect: PG
      host: env:PG_DATABASE_HOST
      port: env:PG_DATABASE_PORT
      username: env:PG_DATABASE_USER
      password: env:PG_DATABASE_PASSWORD
      database: env:PG_DATABASE_NAME
metrics:
  - name: edge_device_up
    type: counter
    description: Edge device is up and running
    labels: device_name, device_ip
  - name: edge_device_down
    type: counter
    description: Edge device is missing
    labels: device_name
expectations:
  - name: devices_up
    metrics:
      - edge_device_up
    datasource: pg_order_db
    query: |
      SELECT 
          device AS device_name,
          ip     AS device_ip
      FROM edge_devices WHERE last_update >= NOW() - INTERVAL "30 minutes"
  - name: devices_down
    metrics:
      - edge_device_up
    datasource: pg_order_db
    query: |
      SELECT 
          device AS device_name,
          ip     AS device_ip
      FROM edge_devices WHERE last_update < NOW() - INTERVAL "30 minutes"
